Add exit handler. Cleans up unfinished files.

diff --git a/ipset_list b/ipset_list
--- a/ipset_list
+++ b/ipset_list
@@ -344,7 +344,7 @@ declare global_delim="${delim:=$default_delim}"
 declare -i global_colorize=${colorize:=0} global_tmout="${set_tmout:=$default_set_tmout}"
 declare -a arr_hsearch=() arr_hsearch_int=() arr_hsearch_xint=() arr_match_on_msum=() arr_opt_int_search=()
 declare -a arr_hxclude=() arr_sxclude=() arr_par=() all_sets=() arr_cmdline=() arr_old_select=() arr_tmp=()
-declare -a arr_test_elem=()
+declare -a arr_test_elem=() arr_files=()
 declare -a arr_main_opts=( "$@" )
 
 # declare standard PATH, if not already defined in environment
@@ -354,7 +354,7 @@ declare -a arr_main_opts=( "$@" )
 : ${cachedir:=/var/cache/ipset_list}
 
 # simple trap
-trap "echo trap on signal activated - exiting; enable exit; exit 111" HUP INT QUIT STOP TERM
+trap "echo trap on signal activated - exiting; ex_handler 111" HUP INT QUIT STOP TERM
 
 # -----------------------------------------------------------------
 # functions
@@ -368,9 +368,18 @@ pe() { # print error
 printf "$*\n" >&2
 }
 
+ex_handler() { # handle exit - cleanup before quitting
+local x
+for x in ${!arr_files[@]}; do
+	pm "Removing unfinished file: \`${arr_files[x]}'"
+	command rm -f "${arr_files[x]}"
+done
+exit ${1:-1}
+}
+
 ex_miss_optarg() { # missing option argument
 pe "$2 of option \`$1' is missing"
-exit 2
+ex_handler 2
 }
 
 ex_err() { # exit on error
@@ -378,7 +387,7 @@ if ((iactive > 1)); then
 	dia_mbox "ERROR: $*"
 else
 	pe "$*"
-	exit 1
+	ex_handler 1
 fi
 }
 
@@ -438,7 +447,7 @@ printf '<%s>%s</%s>\n' "$1" "$2" "$1" >> "$str_cache_xml_file"
 head_val_is_int() { # just for safety, check if expected val is integer
 if ! is_int "$2"; then
 	pe "Headers $1 value \`$2' is not an integer."
-	exit 1
+	ex_handler 1
 fi
 }
 
@@ -1174,15 +1183,18 @@ if ((save_query_plain || save_query_xml)); then
 	if ! [[ -d $cachedir ]]; then
 		if ! command mkdir -p "$cachedir"; then
 			ex_err "Unable to create cache directory: \`$cachedir'."
-			exit 1 # for iactive mode
+			ex_handler 1 # for iactive mode
 		fi
 	fi
 fi
 # write header of file to save representation of the query result as plain ipset commmands
 if ((save_query_plain)); then
-	if ! (set -C; printf '#!/usr/bin/env bash\n' >"$str_cache_plain_file"); then
+	if (set -C; printf '#!/usr/bin/env bash\n' >"$str_cache_plain_file"); then
+		# remember file as long we didn't successfully finish writing to it
+		arr_files[${#arr_files[@]}]="$str_cache_plain_file"
+	else
 		ex_err "Unable to create file: \`$str_cache_plain_file'."
-		exit 1 # for iactive mode
+		ex_handler 1 # for iactive mode
 	fi
 	printf '# Generated by %s at: %s\n' "$me" "$(command date "+%F %T")" >>"$str_cache_plain_file"
 	printf '# QUERY: %s ' "$me" >>"$str_cache_plain_file"
@@ -1193,9 +1205,12 @@ if ((save_query_plain)); then
 fi
 # write header of file to save representation of the query result as xml ipset output
 if ((save_query_xml)); then
-	if ! (set -C; printf '<?xml version="1.0"?>\n\n' >"$str_cache_xml_file"); then
+	if (set -C; printf '<?xml version="1.0"?>\n\n' >"$str_cache_xml_file"); then
+		# remember file as long we didn't successfully finish writing to it
+		arr_files[${#arr_files[@]}]="$str_cache_xml_file"
+	else
 		ex_err "Unable to create file: \`$str_cache_xml_file'."
-		exit 1 # for iactive mode
+		ex_handler 1 # for iactive mode
 	fi
 	printf '<!-- Generated by %s at: %s -->\n' "$me" "$(command date "+%F %T")" >>"$str_cache_xml_file"
 	printf '<!-- QUERY: %s ' "$me" >>"$str_cache_xml_file"
@@ -1278,7 +1293,7 @@ for idx in "${!arr_sets[@]}"; do
 			Members:*) # closes header (if not `ipset -t')
 				if ! ((in_header)); then
 					pe "Unexpected entry: \`$REPLY' - header not opened?"
-					exit 1
+					ex_handler 1
 				fi
 				in_header=0 found_hxclude=0
 				if ((match_on_header)); then
@@ -1305,7 +1320,7 @@ for idx in "${!arr_sets[@]}"; do
 			*) # either in-header, or member entry
 				if ! ((found_set)); then
 					pe "No set opened by \`Name:'. Unexpected entry: \`$REPLY'."
-					exit 1
+					ex_handler 1
 				fi
 				if ((in_header)); then # we should be in the header
 					get_header # retrieve header info
@@ -1511,6 +1526,12 @@ for idx in "${!arr_sets[@]}"; do
 				for i in ${!arr_mcache[@]}; do
 					printf '"$ipset" add %s %s\n' "$str_set" "${arr_mcache[i]}" >> "$str_cache_plain_file"
 				done
+				# successfully finished writing to file, remove from created files list
+				for i in ${!arr_files[@]}; do
+					if [[ ${arr_files[i]} = $str_cache_plain_file ]]; then
+						unset arr_files[i]
+					fi
+				done
 			fi
 			if ((save_query_xml)); then # save query as xml ipset output
 				o_xtag "members"
@@ -1579,6 +1600,12 @@ done
 if ((save_query_xml)); then
 	let tag_idx-=1
 	c_xtag "ipsets"
+	# successfully finished writing to file, remove from created files list
+	for i in ${!arr_files[@]}; do
+		if [[ ${arr_files[i]} = $str_cache_xml_file ]]; then
+			unset arr_files[i]
+		fi
+	done
 fi
 
 # print global counters
